### ISSUE TITLE
build linux package

### ISSUE THREAD

**Issue by looooo** [conda-forge/qtwebkit-feedstock#11]
Is it somehow possible to enable linux for this feedstock and update to qt5.12?

**Comment by gillins** [comment]
Send in a PR :smile: There has been some discussion about getting `qtwebkit` working again here: https://github.com/conda-forge/qgis-feedstock/issues/68 but I don't think anything ever happened...

**Comment by looooo** [comment]
Hmm, I tried building locally, but my motivation was gone after a few attempts...
