### ISSUE TITLE
Revert back to depending on qt instead of qt-main?

### ISSUE THREAD

**Issue by izahn** [conda-forge/qtwebkit-feedstock#20]
Hey folks, I think we may have jumped the gun with https://github.com/conda-forge/qtwebkit-feedstock/pull/18 , now we are blocking https://github.com/conda-forge/qgis-feedstock/pull/226. Should we revert back to depending on `qt` for now?

**Comment by gillins** [comment]
Happy to go with whatever you think. Is `qt-main` still held up on `qtwebengine` ?

**Comment by izahn** [comment]
Great, I'll submit a PR to go back o `qt` for now.

Yeah, the `qtwebengine` PR still hasn't been merged, though it looks like everything is ready. I asked about migration plans in https://github.com/conda-forge/staged-recipes/pull/17233#issuecomment-1030222120 but haven't got a response yet.

There are over 120 conda-forge packages depending on `qt`
```
mamba repoquery whoneeds qt -c conda-forge | cut -d' ' -f2 | uniq | wc -l
132
```
and I think they need to move together, i.e. things won't work if some packages use `qt` and others use `qt-main`. There should be a migration for this, but I'm not sure if or where that is being planned.
